# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test124124():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_124124(self):
    # Test name: 124124
    # Step # | name | target | value | comment
    self.Open_home()
    # 2 | setWindowSize | 1936x1048 |  | 
    self.driver.set_window_size(1936, 1048)
    # 3 | click | css=#menu_link_7 .title |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#menu_link_7 .title").click()
    # 4 | click | css=#menu_link_7 .cls-1 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#menu_link_7 .cls-1").click()
    # 5 | click | linkText=Туры в Карелию |  | 
    self.driver.find_element(By.LINK_TEXT, "Туры в Карелию").click()
    # 6 | click | css=.btn:nth-child(3) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    # 7 | click | linkText=Соловки своими глазами |  | 
    self.driver.find_element(By.LINK_TEXT, "Соловки своими глазами").click()
    # 8 | mouseOver | css=#menu_link_5 .title |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#menu_link_5 .title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | click | css=.callibri_close_svg > rect:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".callibri_close_svg > rect:nth-child(2)").click()
    # 10 | close |  |  | 
    self.driver.close()

  def Open_home(self):
    # 1 | open | /tours/in-karelia/vsya-kareliya-leto.html |  |
    self.driver.get("https://kareliagid.ru/tours/in-karelia/vsya-kareliya-leto.html")
  
